### ISSUE TITLE
Redirect to https

### ISSUE THREAD

**Issue by boriscallens** [vaerenberg/vaerenberg.com#1]
It seems that going to http://vaerenberg.com doesn't redirect to https://vaerenberg.com

**Comment by boriscallens** [comment]
For more info see: https://stackoverflow.com/questions/39244265/azure-web-app-redirect-http-to-https

**Comment by vaerenberg** [comment]
Thanks for noticing. HTTPS Redirection was added as part of the upgrade to .NET Core 2.2. by means of pull request #2.
